### ISSUE TITLE
rust print error

### ISSUE THREAD

**Issue by rfirefly** [Simon-He95/log#3]
https://github.com/Simon-He95/log/blob/b59fd221aae1b619ebdaecc118fd49a9988848f8/src/index.ts#L125C10-L125C11
The print syntax of rust: `println!("${logPrefix} : {}", ${text || '\"\"'});\n`

**Comment by Simon-He95** [comment]
> https://github.com/Simon-He95/log/blob/b59fd221aae1b619ebdaecc118fd49a9988848f8/src/index.ts#L125C10-L125C11 The print syntax of rust: `println!("${logPrefix} : {}", ${text || '\"\"'});\n`

fixed by v0.0.5
